apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: flask-monitoring
spec:
  replicas: 1
  selector:
    app: flask-monitoring
  template:
    metadata:
      labels:
        app: flask-monitoring
    spec:
      containers:
        - name: flask-monitoring
          image: image-registry.openshift-image-registry.svc:5000/deepakagrawalmsoe-dev/flask-monitoring:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: openshift-token
                  key: token
  strategy:
    type: Rolling
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - flask-monitoring
        from:
          kind: ImageStreamTag
          name: 'flask-monitoring:latest'
---
apiVersion: v1
kind: Service
metadata:
  name: flask-monitoring
spec:
  selector:
    app: flask-monitoring
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flask-monitoring
spec:
  to:
    kind: Service
    name: flask-monitoring
  port:
    targetPort: 5000
