apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-dashboard
  namespace: deepakagrawalmsoe-dev
  labels:
    app: react-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-dashboard
  template:
    metadata:
      labels:
        app: react-dashboard
    spec:
      containers:
        - name: react-dashboard
          image: image-registry.openshift-image-registry.svc:5000/deepakagrawalmsoe-dev/react-dashboard:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: react-dashboard-service
  namespace: deepakagrawalmsoe-dev
  labels:
    app: react-dashboard
spec:
  selector:
    app: react-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: react-dashboard-route
  namespace: deepakagrawalmsoe-dev
  labels:
    app: react-dashboard
spec:
  to:
    kind: Service
    name: react-dashboard-service
  port:
    targetPort: 80
  tls:
    termination: edge
  wildcardPolicy: None

