apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-monitoring-hpa
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: flask-monitoring
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
